---

- name: Setting build series
  template:
    src: "{{ program_name }}-changelog.j2"
    dest: "{{ build_location }}/{{ src }}/debian/changelog"
  tags:
    - build_deb

- name: Building deb
  command: "debuild -us -uc -b"
  args:
    chdir: "{{ build_location }}/{{ src }}"
  register: debuild_result
  tags:
    - build_deb

- name: Signing deb
  command: "debuild -S -sa -k{{ GPGKEY }}"
  args:
    chdir: "{{ build_location }}/{{ src }}"
  register: debuild_sign_result
  when:
    - "debuild_result.rc == 0"
    - GPGKEY is defined
  tags:
    - build_deb

- name: Find source changes
  find:
    paths: "{{ build_location }}/"
    patterns: "*_source.changes"
  register: source_changes

- name: Uploading deb
  command: "dput ppa:gale-michael/netflow-tools-ppa {{ source_changes.files[0].path }}"
  args:
    chdir: "{{ build_location }}"
  register: dput_result
  when:
    - "source_changes.matched == 1"
