---

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 300
  become: yes
  tags:
    - packages

- name: Install list of packages
  apt:
    name: "{{ item }}"
    state: installed
  become: yes
  with_items: "{{ required_packages }}"
  tags:
    - packages
